# fly.toml app configuration file for halal-bot-clean

app = 'halal-bot-clean'
primary_region = 'fra'

[build]
  command = "python main.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
